FROM node:latest AS client
LABEL version="1.0"
LABEL description ="This is frontend for ricebowl-recipes"

WORKDIR /app
RUN mkdir /client
WORKDIR /app/client
COPY . /app/client
RUN ls -l

RUN npm install --production

EXPOSE 8080
CMD ["npm","start"]