# FROM node:latest AS client
# LABEL version="1.0"
# LABEL description ="This is frontend for ricebowl-recipes"

# WORKDIR /app
# RUN mkdir /client
# WORKDIR /app/client
# COPY . /app/client
# RUN ls -l

# RUN npm install --production

# EXPOSE 8080
# CMD ["npm","start"]


FROM node:latest as build-step

WORKDIR /app
RUN mkdir /client
WORKDIR /app/client
COPY . /app/client
RUN ls -l

RUN npm install --production
RUN npm run build

FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf 
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/configfile.template
COPY --from=build-step /app/client/build /usr/share/nginx/html

ENV PORT 8080
ENV HOST 0.0.0.0
EXPOSE 8080

CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
