FROM node:latest AS client

LABEL version="1.0"
LABEL description ="This is frontend for ricebowl-recipes"

WORKDIR /app
RUN mkdir /client
WORKDIR /app/client
COPY . /app/client
RUN ls -l

RUN npm install --production
RUN npm run build

RUN ls -l
EXPOSE 3000

FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
RUN rm /etc/nginx/conf.d/default.conf
RUN chmod -R a+w /var/cache/nginx/ \
        && touch /var/run/nginx.pid \
        && chmod a+w /var/run/nginx.pid

COPY --from=client /app/client/build /usr/share/nginx/html
COPY --from=client /app/client/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
CMD ["service","nginx","start"]

CMD ["nginx","-g","daemon off;"]