const meals = [
  {
    recipeid: 1,
    name: 'Chicken Pizza',
    rating: 5,
    category: ['Chinese'],
    prepHour: 2,
    cookingHour: 2,
  },
  {
    recipeid: 2,
    name: 'Chicken Pizza',
    rating: 4,
    category: ['Mexican'],
    prepHour: 2,
    cookingHour: 2,
  },
  {
    recipeid: 3,
    name: 'Cheese Burger',
    rating: 3,
    category: ['American'],
    prepHour: 1,
    cookingHour: 0.5,
  },
];

const weekData = {
  lists: {
    'list-1': {
      id: 'list-1',
      title: 'Sunday',
      meals: {
        breakfast: [
          {
            recipeid: 1,
            name: 'Bacon Egg Tacos',
            rating: 5,
            category: ['Lightdish'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
          {
            recipeid: 2,
            name: 'Oven Baked Omelet',
            rating: 4,
            category: ['Breakfast'],
            prepHour: 0.5,
            cookingHour: 1,
          },
        ],
        lunch: [
          {
            recipeid: 3,
            name: 'Pumpkin Chili',
            rating: 5,
            category: ['Mexican'],
            prepHour: 2,
            cookingHour: 2,
          },
          {
            recipeid: 4,
            name: 'Butternut Squash',
            rating: 4,
            category: ['Homemade'],
            prepHour: 2,
            cookingHour: 2,
          },
        ],
        dinner: [
          {
            recipeid: 5,
            name: 'Steak Frites',
            rating: 5,
            category: ['Heavy'],
            prepHour: 1,
            cookingHour: 2,
          },
          {
            recipeid: 6,
            name: 'Caesar Salad',
            rating: 4,
            category: ['Healthy'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
        ],
      },
    },
    'list-2': {
      id: 'list-2',
      title: 'Monday',
      meals: {
        breakfast: [
          {
            recipeid: 1,
            name: 'Bacon Egg Tacos',
            rating: 5,
            category: ['Lightdish'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
          {
            recipeid: 2,
            name: 'Oven Baked Omelet',
            rating: 4,
            category: ['Breakfast'],
            prepHour: 0.5,
            cookingHour: 1,
          },
        ],
        lunch: [
          {
            recipeid: 3,
            name: 'Pumpkin Chili',
            rating: 5,
            category: ['Mexican'],
            prepHour: 2,
            cookingHour: 2,
          },
          {
            recipeid: 4,
            name: 'Butternut Squash',
            rating: 4,
            category: ['Homemade'],
            prepHour: 2,
            cookingHour: 2,
          },
        ],
        dinner: [
          {
            recipeid: 5,
            name: 'Steak Frites',
            rating: 5,
            category: ['Heavy'],
            prepHour: 1,
            cookingHour: 2,
          },
          {
            recipeid: 6,
            name: 'Caesar Salad',
            rating: 4,
            category: ['Healthy'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
        ],
      },
    },

    'list-3': {
      id: 'list-3',
      title: 'Tuesday',
      meals: {
        breakfast: [
          {
            recipeid: 1,
            name: 'Bacon Egg Tacos',
            rating: 5,
            category: ['Lightdish'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
          {
            recipeid: 2,
            name: 'Oven Baked Omelet',
            rating: 4,
            category: ['Breakfast'],
            prepHour: 0.5,
            cookingHour: 1,
          },
        ],
        lunch: [
          {
            recipeid: 3,
            name: 'Pumpkin Chili',
            rating: 5,
            category: ['Mexican'],
            prepHour: 2,
            cookingHour: 2,
          },
          {
            recipeid: 4,
            name: 'Butternut Squash',
            rating: 4,
            category: ['Homemade'],
            prepHour: 2,
            cookingHour: 2,
          },
        ],
        dinner: [
          {
            recipeid: 5,
            name: 'Steak Frites',
            rating: 5,
            category: ['Heavy'],
            prepHour: 1,
            cookingHour: 2,
          },
          {
            recipeid: 6,
            name: 'Caesar Salad',
            rating: 4,
            category: ['Healthy'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
        ],
      },
    },
    'list-4': {
      id: 'list-4',
      title: 'Wednesday',
      meals: {
        breakfast: [
          {
            recipeid: 1,
            name: 'Bacon Egg Tacos',
            rating: 5,
            category: ['Lightdish'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
          {
            recipeid: 2,
            name: 'Oven Baked Omelet',
            rating: 4,
            category: ['Breakfast'],
            prepHour: 0.5,
            cookingHour: 1,
          },
        ],
        lunch: [
          {
            recipeid: 3,
            name: 'Pumpkin Chili',
            rating: 5,
            category: ['Mexican'],
            prepHour: 2,
            cookingHour: 2,
          },
          {
            recipeid: 4,
            name: 'Butternut Squash',
            rating: 4,
            category: ['Homemade'],
            prepHour: 2,
            cookingHour: 2,
          },
        ],
        dinner: [
          {
            recipeid: 5,
            name: 'Steak Frites',
            rating: 5,
            category: ['Heavy'],
            prepHour: 1,
            cookingHour: 2,
          },
          {
            recipeid: 6,
            name: 'Caesar Salad',
            rating: 4,
            category: ['Healthy'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
        ],
      },
    },
    'list-5': {
      id: 'list-5',
      title: 'Thursday',
      meals: {
        breakfast: [
          {
            recipeid: 1,
            name: 'Bacon Egg Tacos',
            rating: 5,
            category: ['Lightdish'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
          {
            recipeid: 2,
            name: 'Oven Baked Omelet',
            rating: 4,
            category: ['Breakfast'],
            prepHour: 0.5,
            cookingHour: 1,
          },
        ],
        lunch: [
          {
            recipeid: 3,
            name: 'Pumpkin Chili',
            rating: 5,
            category: ['Mexican'],
            prepHour: 2,
            cookingHour: 2,
          },
          {
            recipeid: 4,
            name: 'Butternut Squash',
            rating: 4,
            category: ['Homemade'],
            prepHour: 2,
            cookingHour: 2,
          },
        ],
        dinner: [
          {
            recipeid: 5,
            name: 'Steak Frites',
            rating: 5,
            category: ['Heavy'],
            prepHour: 1,
            cookingHour: 2,
          },
          {
            recipeid: 6,
            name: 'Caesar Salad',
            rating: 4,
            category: ['Healthy'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
        ],
      },
    },
    'list-6': {
      id: 'list-6',
      title: 'Friday',
      meals: {
        breakfast: [
          {
            recipeid: 1,
            name: 'Bacon Egg Tacos',
            rating: 5,
            category: ['Lightdish'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
          {
            recipeid: 2,
            name: 'Oven Baked Omelet',
            rating: 4,
            category: ['Breakfast'],
            prepHour: 0.5,
            cookingHour: 1,
          },
        ],
        lunch: [
          {
            recipeid: 3,
            name: 'Pumpkin Chili',
            rating: 5,
            category: ['Mexican'],
            prepHour: 2,
            cookingHour: 2,
          },
          {
            recipeid: 4,
            name: 'Butternut Squash',
            rating: 4,
            category: ['Homemade'],
            prepHour: 2,
            cookingHour: 2,
          },
        ],
        dinner: [
          {
            recipeid: 5,
            name: 'Steak Frites',
            rating: 5,
            category: ['Heavy'],
            prepHour: 1,
            cookingHour: 2,
          },
          {
            recipeid: 6,
            name: 'Caesar Salad',
            rating: 4,
            category: ['Healthy'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
        ],
      },
    },
    'list-7': {
      id: 'list-7',
      title: 'Saturday',
      meals: {
        breakfast: [
          {
            recipeid: 1,
            name: 'Bacon Egg Tacos',
            rating: 5,
            category: ['Lightdish'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
          {
            recipeid: 2,
            name: 'Oven Baked Omelet',
            rating: 4,
            category: ['Breakfast'],
            prepHour: 0.5,
            cookingHour: 1,
          },
        ],
        lunch: [
          {
            recipeid: 3,
            name: 'Pumpkin Chili',
            rating: 5,
            category: ['Mexican'],
            prepHour: 2,
            cookingHour: 2,
          },
          {
            recipeid: 4,
            name: 'Butternut Squash',
            rating: 4,
            category: ['Homemade'],
            prepHour: 2,
            cookingHour: 2,
          },
        ],
        dinner: [
          {
            recipeid: 5,
            name: 'Steak Frites',
            rating: 5,
            category: ['Heavy'],
            prepHour: 1,
            cookingHour: 2,
          },
          {
            recipeid: 6,
            name: 'Caesar Salad',
            rating: 4,
            category: ['Healthy'],
            prepHour: 0.5,
            cookingHour: 0.25,
          },
        ],
      },
    },
  },
  listsIdx: [
    'list-1',
    'list-2',
    'list-3',
    'list-4',
    'list-5',
    'list-6',
    'list-7',
  ],
};

export default weekData;
